/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LivrosController;
import Model.LivrosModel;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CadastroLivro extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLivro
     */
    public CadastroLivro() {
        initComponents();
        listarLivrosView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        JTLivros = new javax.swing.JTable();
        JPButtons = new javax.swing.JPanel();
        BtnDeletar = new javax.swing.JButton();
        BtnAlterar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        JLPesquisa = new javax.swing.JLabel();
        TxtPesquisa = new javax.swing.JTextField();
        BtnPesquisa = new javax.swing.JButton();
        BtnConfirma = new javax.swing.JButton();
        JLId = new javax.swing.JLabel();
        JPCadastroLivro = new javax.swing.JPanel();
        JLTitulo = new javax.swing.JLabel();
        TxtTituloLivro = new javax.swing.JTextField();
        JLGenero = new javax.swing.JLabel();
        TxtGenero = new javax.swing.JTextField();
        TxtNumeroPaginas = new javax.swing.JTextField();
        JLNumeroPaginas = new javax.swing.JLabel();
        JLResumo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAResumo = new javax.swing.JTextArea();
        JLCadastroLivro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Gênero", "Numero de Paginas", "Resumo", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTLivrosMouseClicked(evt);
            }
        });
        JTLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTLivrosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTLivrosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(JTLivros);
        if (JTLivros.getColumnModel().getColumnCount() > 0) {
            JTLivros.getColumnModel().getColumn(1).setResizable(false);
            JTLivros.getColumnModel().getColumn(3).setResizable(false);
        }

        JPButtons.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        BtnDeletar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnDeletar.setText("Deletar");
        BtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletarActionPerformed(evt);
            }
        });

        BtnAlterar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnAlterar.setText("Alterar");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        BtnSalvar.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        JLPesquisa.setText("Pesquisa: ");

        TxtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPesquisaActionPerformed(evt);
            }
        });

        BtnPesquisa.setText("Pesquisar");
        BtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisaActionPerformed(evt);
            }
        });

        BtnConfirma.setText("Confirmar Alteração");
        BtnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPButtonsLayout = new javax.swing.GroupLayout(JPButtons);
        JPButtons.setLayout(JPButtonsLayout);
        JPButtonsLayout.setHorizontalGroup(
            JPButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPButtonsLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(BtnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDeletar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnConfirma)
                .addGap(18, 18, 18)
                .addComponent(JLPesquisa)
                .addGap(18, 18, 18)
                .addComponent(TxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnPesquisa)
                .addContainerGap())
        );
        JPButtonsLayout.setVerticalGroup(
            JPButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPButtonsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(JPButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnDeletar)
                    .addComponent(JLPesquisa)
                    .addComponent(TxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesquisa)
                    .addComponent(BtnConfirma))
                .addGap(14, 14, 14))
        );

        JPCadastroLivro.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        JLTitulo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        JLTitulo.setText("Título:");

        TxtTituloLivro.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        JLGenero.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        JLGenero.setText("Gênero:");

        TxtGenero.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        TxtNumeroPaginas.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        JLNumeroPaginas.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        JLNumeroPaginas.setText("Número de Paginas:");

        JLResumo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        JLResumo.setText("Resumo ");

        JTAResumo.setColumns(20);
        JTAResumo.setRows(5);
        jScrollPane1.setViewportView(JTAResumo);

        JLCadastroLivro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        JLCadastroLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLCadastroLivro.setText("Cadastro Do Livro");

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Livro");

        jButton2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton2.setText("Emprestimo ");

        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setText("Autor");

        javax.swing.GroupLayout JPCadastroLivroLayout = new javax.swing.GroupLayout(JPCadastroLivro);
        JPCadastroLivro.setLayout(JPCadastroLivroLayout);
        JPCadastroLivroLayout.setHorizontalGroup(
            JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCadastroLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLTitulo)
                    .addComponent(JLNumeroPaginas)
                    .addComponent(JLGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtNumeroPaginas)
                    .addComponent(TxtTituloLivro)
                    .addComponent(TxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLResumo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPCadastroLivroLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(JLCadastroLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );
        JPCadastroLivroLayout.setVerticalGroup(
            JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCadastroLivroLayout.createSequentialGroup()
                .addGroup(JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCadastroLivroLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(JLCadastroLivro))
                    .addGroup(JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1)
                        .addComponent(jButton3)))
                .addGap(44, 44, 44)
                .addGroup(JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLTitulo)
                    .addComponent(TxtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLResumo))
                .addGroup(JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCadastroLivroLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLGenero)
                            .addComponent(TxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(JPCadastroLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNumeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLNumeroPaginas)))
                    .addGroup(JPCadastroLivroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JPCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)
                            .addComponent(JPButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(418, 418, 418)
                    .addComponent(JLId)
                    .addContainerGap(459, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(JPCadastroLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JPButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(JLId)
                    .addContainerGap(310, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletarActionPerformed
        // TODO add your handling code here:
        String idAuxiliar = JLId.getText();
        String titulo = TxtTituloLivro.getText();
        String genero = TxtGenero.getText();
        String numeroPaginas = TxtNumeroPaginas.getText();
        String resumo = JTAResumo.getText();

        Integer id = Integer.valueOf(idAuxiliar);

        LivrosController excluirLivros = new LivrosController();
        excluirLivros.excluirLivrosController(id);
        listarLivrosView();

        TxtTituloLivro.setText("");
        TxtNumeroPaginas.setText("");
        JTAResumo.setText("");
        TxtGenero.setText("");

        BtnSalvar.setEnabled(true);
        listarLivrosView();
    }//GEN-LAST:event_BtnDeletarActionPerformed

    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        // TODO add your handling code here:
        preencheDados();

    }//GEN-LAST:event_BtnAlterarActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        // TODO add your handling code here:
        String titulo = TxtTituloLivro.getText();
        String genero = TxtGenero.getText();
        String numeroPaginasT = TxtNumeroPaginas.getText();
        String resumo = JTAResumo.getText();
         String status = "Disponivel";

        Integer numeroPaginas = Integer.parseInt(numeroPaginasT);

        LivrosController novoCadastro = new LivrosController();

        novoCadastro.CadastroLivrosController(titulo, genero, numeroPaginas, resumo, status);

        JTAResumo.setText("");
        TxtTituloLivro.setText("");
        TxtGenero.setText("");
        TxtNumeroPaginas.setText("");

        listarLivrosView();
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void TxtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPesquisaActionPerformed

    private void BtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisaActionPerformed
        // TODO add your handling code here:
        String pesquisa = TxtPesquisa.getText();
        filtrarLivros(pesquisa);
    }//GEN-LAST:event_BtnPesquisaActionPerformed

    private void BtnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmaActionPerformed
        // TODO add your handling code here:
        String idAux = JLId.getText();
        String titulo = TxtTituloLivro.getText();
        String genero = TxtGenero.getText();
        String numeroPaginasT = TxtNumeroPaginas.getText();
        String resumo = JTAResumo.getText();
       

        Integer numeroPaginas = Integer.parseInt(numeroPaginasT);

        LivrosController AlterarLivros = new LivrosController();
        AlterarLivros.alterarLivrosController(idAux, titulo, genero, numeroPaginas, resumo);
        BtnSalvar.setEnabled(true);
        listarLivrosView();
    }//GEN-LAST:event_BtnConfirmaActionPerformed

    private void JTLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTLivrosMouseClicked
        // TODO add your handling code here:
        CapturaDados();
    }//GEN-LAST:event_JTLivrosMouseClicked

    private void JTLivrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTLivrosKeyPressed
        // TODO add your handling code here:
        String id = JTLivros.getModel().getValueAt(JTLivros.getSelectedRow(), 0).toString();

    }//GEN-LAST:event_JTLivrosKeyPressed

    private void JTLivrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTLivrosKeyReleased
        // TODO add your handling code here:
        String id = JTLivros.getModel().getValueAt(JTLivros.getSelectedRow(), 0).toString();

    }//GEN-LAST:event_JTLivrosKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnConfirma;
    private javax.swing.JButton BtnDeletar;
    private javax.swing.JButton BtnPesquisa;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JLabel JLCadastroLivro;
    private javax.swing.JLabel JLGenero;
    private javax.swing.JLabel JLId;
    private javax.swing.JLabel JLNumeroPaginas;
    private javax.swing.JLabel JLPesquisa;
    private javax.swing.JLabel JLResumo;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JPanel JPButtons;
    private javax.swing.JPanel JPCadastroLivro;
    private javax.swing.JTextArea JTAResumo;
    private javax.swing.JTable JTLivros;
    private javax.swing.JTextField TxtGenero;
    private javax.swing.JTextField TxtNumeroPaginas;
    private javax.swing.JTextField TxtPesquisa;
    private javax.swing.JTextField TxtTituloLivro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void listarLivrosView() {
        DefaultTableModel dtm = (DefaultTableModel) JTLivros.getModel();
        dtm.setRowCount(0);
        LivrosController livrosController = new LivrosController();
        ArrayList<LivrosModel> listarLivros = livrosController.listarLivrosController();

        Iterator<LivrosModel> iterator = listarLivros.iterator();

        while (iterator.hasNext()) {
            LivrosModel livros = iterator.next();
            dtm.addRow(new Object[]{
                livros.getCodigo(),
                livros.getTitulo(),
                livros.getGenero(),
                livros.getNumeroPaginas(),
                livros.getResumo(),
                livros.getStatus()});
        }
    }

    private void filtrarLivros(String pesquisa) {
        DefaultTableModel dtm = (DefaultTableModel) JTLivros.getModel();
        dtm.setRowCount(0);
        LivrosController livrosController = new LivrosController();
        ArrayList<LivrosModel> listarLivros = livrosController.buscarLivrosController(pesquisa);

        Iterator<LivrosModel> iterator = listarLivros.iterator();
        while (iterator.hasNext()) {
            LivrosModel livros = iterator.next();
            dtm.addRow(new Object[]{
                livros.getCodigo(),
                livros.getTitulo(),
                livros.getGenero(),
                livros.getNumeroPaginas(),
                livros.getResumo(),
                livros.getStatus()});
        }
    }

    private void preencheDados() {
        String titulo = JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 1)
                .toString();
        String genero = JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 2)
                .toString();
        String numeroPaginas = JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 3)
                .toString();
        String resumo = JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 4)
                .toString();
        String status = JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 5)
                .toString();
        String idAux = JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 0)
                .toString();

        TxtTituloLivro.setText(titulo);
        TxtGenero.setText(genero);
        TxtNumeroPaginas.setText(numeroPaginas);
        JTAResumo.setText(resumo);
        JLId.setText(idAux);
        

        BtnSalvar.setEnabled(false);
    }

    private void CapturaDados() {
        String titulo= JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 1)
                .toString();
        String genero = JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 2)
                .toString();
        String numeroPaginas= JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 3)
                .toString();
        String resumo = JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 4)
                .toString();
        String status = JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 5)
                .toString();
        String idAux = JTLivros.getModel().
                getValueAt(JTLivros.getSelectedRow(), 0)
                .toString();
    }
}
